-- PcPos Uyumluluk Scripti
-- Bu scripti PostgreSQL veritabanınızda manuel çalıştırın.
-- dotnet ef database update bu migration'ları tanımadığı için SQL ile uygulanmalı.

-- 1. Product.CategoryId (AddCategoryIdToProduct)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'Product' AND column_name = 'CategoryId') THEN
        ALTER TABLE "Product" ADD COLUMN "CategoryId" integer NULL;
        CREATE INDEX IF NOT EXISTS "IX_Product_CategoryId" ON "Product" ("CategoryId");
        -- FK opsiyonel: Bazı DB'lerde unique constraint hatası verebilir
        -- ALTER TABLE "Product" ADD CONSTRAINT "FK_Product_Category_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Category" ("Id");
    END IF;
END $$;

-- 2. AspNetUsers.IsActive
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'AspNetUsers' AND column_name = 'IsActive') THEN
        ALTER TABLE "AspNetUsers" ADD COLUMN "IsActive" boolean NOT NULL DEFAULT true;
    END IF;
END $$;

-- 3. Customers.CompanyCode
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'Customers' AND column_name = 'CompanyCode') THEN
        ALTER TABLE "Customers" ADD COLUMN "CompanyCode" character varying(50) NULL;
    END IF;
END $$;

-- 4. VersionApp tablosu
CREATE TABLE IF NOT EXISTS "VersionApp" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PcPosVersion" character varying(50) NOT NULL
);

-- Varsayılan sürüm kaydı (tablo boşsa)
INSERT INTO "VersionApp" ("PcPosVersion") 
SELECT '1.0.0' WHERE NOT EXISTS (SELECT 1 FROM "VersionApp" LIMIT 1);

-- 5. TransactionMaster ve tTransaction KALDIRILDI - CustomerAccountTransaction kullanılacak
