using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ecommerce.EFCore.Migrations
{
    /// <inheritdoc />
    public partial class AddPushNotificationTables : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Tüm değişiklikler koşullu — veritabanı ile migration state uyumsuzluğunu tolere eder
            migrationBuilder.Sql(@"
                -- VinExternalScrapedData kolonları
                DO $$ BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='VinExternalScrapedData' AND column_name='ManufacturerCode') THEN
                        ALTER TABLE ""VinExternalScrapedData"" ADD COLUMN ""ManufacturerCode"" text;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='VinExternalScrapedData' AND column_name='ModelCode') THEN
                        ALTER TABLE ""VinExternalScrapedData"" ADD COLUMN ""ModelCode"" text;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='VinExternalScrapedData' AND column_name='VehicleCode') THEN
                        ALTER TABLE ""VinExternalScrapedData"" ADD COLUMN ""VehicleCode"" text;
                    END IF;
                END $$;

                -- UserCars PlateNumber nullable yap
                DO $$ BEGIN
                    ALTER TABLE ""UserCars"" ALTER COLUMN ""PlateNumber"" DROP NOT NULL;
                EXCEPTION WHEN others THEN NULL;
                END $$;

                -- UserCars ApplicationUserId kolonu
                DO $$ BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='UserCars' AND column_name='ApplicationUserId') THEN
                        ALTER TABLE ""UserCars"" ADD COLUMN ""ApplicationUserId"" integer;
                    END IF;
                END $$;

                -- NotificationLogs tablosu
                CREATE TABLE IF NOT EXISTS ""NotificationLogs"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Title"" text NOT NULL,
                    ""Body"" text NOT NULL,
                    ""DeepLink"" text,
                    ""TargetAudience"" text NOT NULL,
                    ""SentByUserId"" integer,
                    ""SentAt"" timestamp with time zone NOT NULL,
                    ""TotalTargets"" integer NOT NULL DEFAULT 0,
                    ""SuccessCount"" integer NOT NULL DEFAULT 0,
                    ""FailureCount"" integer NOT NULL DEFAULT 0,
                    ""ErrorDetails"" text,
                    CONSTRAINT ""PK_NotificationLogs"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_NotificationLogs_AspNetUsers_SentByUserId"" FOREIGN KEY (""SentByUserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE SET NULL
                );

                -- UserPushTokens tablosu
                CREATE TABLE IF NOT EXISTS ""UserPushTokens"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""UserId"" integer NOT NULL,
                    ""Token"" text NOT NULL,
                    ""Platform"" character varying(10) NOT NULL,
                    ""DeviceId"" text NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NOT NULL,
                    ""IsActive"" boolean NOT NULL DEFAULT true,
                    CONSTRAINT ""PK_UserPushTokens"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_UserPushTokens_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
                );

                -- UserNotifications tablosu (kullanıcıya özel bildirim kayıtları)
                CREATE TABLE IF NOT EXISTS ""UserNotifications"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""UserId"" integer NOT NULL,
                    ""Title"" text NOT NULL,
                    ""Body"" text NOT NULL,
                    ""DeepLink"" text,
                    ""IsRead"" boolean NOT NULL DEFAULT false,
                    ""IsDeleted"" boolean NOT NULL DEFAULT false,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""ReadAt"" timestamp with time zone,
                    ""NotificationLogId"" integer,
                    CONSTRAINT ""PK_UserNotifications"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_UserNotifications_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE,
                    CONSTRAINT ""FK_UserNotifications_NotificationLogs_NotificationLogId"" FOREIGN KEY (""NotificationLogId"") REFERENCES ""NotificationLogs"" (""Id"") ON DELETE SET NULL
                );

                -- Index'ler (koşullu)
                CREATE INDEX IF NOT EXISTS ""IX_UserCars_ApplicationUserId"" ON ""UserCars"" (""ApplicationUserId"");
                CREATE INDEX IF NOT EXISTS ""IX_NotificationLogs_SentAt"" ON ""NotificationLogs"" (""SentAt"");
                CREATE INDEX IF NOT EXISTS ""IX_NotificationLogs_SentByUserId"" ON ""NotificationLogs"" (""SentByUserId"");
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_UserPushTokens_UserId_DeviceId"" ON ""UserPushTokens"" (""UserId"", ""DeviceId"");
                CREATE INDEX IF NOT EXISTS ""IX_UserNotifications_UserId"" ON ""UserNotifications"" (""UserId"");
                CREATE INDEX IF NOT EXISTS ""IX_UserNotifications_NotificationLogId"" ON ""UserNotifications"" (""NotificationLogId"");
                CREATE INDEX IF NOT EXISTS ""IX_UserNotifications_CreatedAt"" ON ""UserNotifications"" (""CreatedAt"" DESC);

                -- UserCars FK (koşullu)
                DO $$ BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_UserCars_AspNetUsers_ApplicationUserId') THEN
                        ALTER TABLE ""UserCars"" ADD CONSTRAINT ""FK_UserCars_AspNetUsers_ApplicationUserId"" FOREIGN KEY (""ApplicationUserId"") REFERENCES ""AspNetUsers"" (""Id"");
                    END IF;
                END $$;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                DO $$ BEGIN
                    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_UserCars_AspNetUsers_ApplicationUserId') THEN
                        ALTER TABLE ""UserCars"" DROP CONSTRAINT ""FK_UserCars_AspNetUsers_ApplicationUserId"";
                    END IF;
                END $$;

                DROP TABLE IF EXISTS ""NotificationLogs"";
                DROP TABLE IF EXISTS ""UserPushTokens"";
                DROP INDEX IF EXISTS ""IX_UserCars_ApplicationUserId"";

                DO $$ BEGIN
                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='VinExternalScrapedData' AND column_name='ManufacturerCode') THEN
                        ALTER TABLE ""VinExternalScrapedData"" DROP COLUMN ""ManufacturerCode"";
                    END IF;
                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='VinExternalScrapedData' AND column_name='ModelCode') THEN
                        ALTER TABLE ""VinExternalScrapedData"" DROP COLUMN ""ModelCode"";
                    END IF;
                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='VinExternalScrapedData' AND column_name='VehicleCode') THEN
                        ALTER TABLE ""VinExternalScrapedData"" DROP COLUMN ""VehicleCode"";
                    END IF;
                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='UserCars' AND column_name='ApplicationUserId') THEN
                        ALTER TABLE ""UserCars"" DROP COLUMN ""ApplicationUserId"";
                    END IF;
                END $$;
            ");
        }
    }
}
