// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ecommerce.EFCore.Context;

#nullable disable

namespace ecommerce.EFCore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260306120001_BankAccountPaymentTypeId")]
    partial class BankAccountPaymentTypeId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Designer used for migration reference - model snapshot is source of truth
#pragma warning restore 612, 618
        }
    }
}
