using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ecommerce.EFCore.Migrations
{
    /// <inheritdoc />
    public partial class AddCustomerAccountTransaction : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Add Orders.InvoiceId column if it doesn't exist
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Orders' AND column_name = 'InvoiceId') THEN
                        ALTER TABLE ""Orders"" ADD COLUMN ""InvoiceId"" integer;
                    END IF;
                END $$;
            ");

            // Add Invoices.OrderId column if it doesn't exist
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Invoices' AND column_name = 'OrderId') THEN
                        ALTER TABLE ""Invoices"" ADD COLUMN ""OrderId"" integer;
                    END IF;
                END $$;
            ");

            // Create CustomerAccountTransactions table if it doesn't exist
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""CustomerAccountTransactions"" (
                    ""CreatedDate"" timestamp with time zone NOT NULL,
                    ""ModifiedDate"" timestamp with time zone,
                    ""DeletedDate"" timestamp with time zone,
                    ""Id"" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                    ""CustomerId"" integer NOT NULL,
                    ""OrderId"" integer,
                    ""InvoiceId"" integer,
                    ""TransactionType"" smallint NOT NULL,
                    ""Amount"" numeric(18,2) NOT NULL,
                    ""TransactionDate"" timestamp with time zone NOT NULL,
                    ""Description"" character varying(500),
                    ""PaymentTypeId"" integer,
                    ""CashRegisterId"" integer,
                    ""ReferenceNo"" character varying(50),
                    ""BalanceAfterTransaction"" numeric(18,2) NOT NULL,
                    ""Status"" integer NOT NULL,
                    ""CreatedId"" integer NOT NULL,
                    ""ModifiedId"" integer,
                    ""DeletedId"" integer,
                    CONSTRAINT ""PK_CustomerAccountTransactions"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_CustomerAccountTransactions_CashRegisters_CashRegisterId"" FOREIGN KEY (""CashRegisterId"") REFERENCES ""CashRegisters"" (""Id""),
                    CONSTRAINT ""FK_CustomerAccountTransactions_Customers_CustomerId"" FOREIGN KEY (""CustomerId"") REFERENCES ""Customers"" (""Id"") ON DELETE CASCADE,
                    CONSTRAINT ""FK_CustomerAccountTransactions_Invoices_InvoiceId"" FOREIGN KEY (""InvoiceId"") REFERENCES ""Invoices"" (""Id""),
                    CONSTRAINT ""FK_CustomerAccountTransactions_Orders_OrderId"" FOREIGN KEY (""OrderId"") REFERENCES ""Orders"" (""Id"")
                );
            ");

            // Create indexes if they don't exist
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_Orders_InvoiceId') THEN
                        CREATE INDEX ""IX_Orders_InvoiceId"" ON ""Orders"" (""InvoiceId"");
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_Invoices_OrderId') THEN
                        CREATE INDEX ""IX_Invoices_OrderId"" ON ""Invoices"" (""OrderId"");
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_CustomerAccountTransactions_CashRegisterId') THEN
                        CREATE INDEX ""IX_CustomerAccountTransactions_CashRegisterId"" ON ""CustomerAccountTransactions"" (""CashRegisterId"");
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_CustomerAccountTransactions_CustomerId') THEN
                        CREATE INDEX ""IX_CustomerAccountTransactions_CustomerId"" ON ""CustomerAccountTransactions"" (""CustomerId"");
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_CustomerAccountTransactions_InvoiceId') THEN
                        CREATE INDEX ""IX_CustomerAccountTransactions_InvoiceId"" ON ""CustomerAccountTransactions"" (""InvoiceId"");
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_CustomerAccountTransactions_OrderId') THEN
                        CREATE INDEX ""IX_CustomerAccountTransactions_OrderId"" ON ""CustomerAccountTransactions"" (""OrderId"");
                    END IF;
                END $$;
            ");

            // Add foreign keys if they don't exist
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Invoices_Orders_OrderId') THEN
                        ALTER TABLE ""Invoices"" ADD CONSTRAINT ""FK_Invoices_Orders_OrderId"" FOREIGN KEY (""OrderId"") REFERENCES ""Orders"" (""Id"");
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Orders_Invoices_InvoiceId') THEN
                        ALTER TABLE ""Orders"" ADD CONSTRAINT ""FK_Orders_Invoices_InvoiceId"" FOREIGN KEY (""InvoiceId"") REFERENCES ""Invoices"" (""Id"");
                    END IF;
                END $$;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Invoices_Orders_OrderId",
                table: "Invoices");

            migrationBuilder.DropForeignKey(
                name: "FK_Orders_Invoices_InvoiceId",
                table: "Orders");

            migrationBuilder.DropTable(
                name: "CustomerAccountTransactions");

            migrationBuilder.DropIndex(
                name: "IX_Orders_InvoiceId",
                table: "Orders");

            migrationBuilder.DropIndex(
                name: "IX_Invoices_OrderId",
                table: "Invoices");

            migrationBuilder.DropColumn(
                name: "InvoiceId",
                table: "Orders");

            migrationBuilder.DropColumn(
                name: "OrderId",
                table: "Invoices");
        }
    }
}
