//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.Admin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Culture_TR {

#pragma warning disable CS0649 // Field is assigned by reflection in resource loader
        private static global::System.Resources.ResourceManager resourceMan;
#pragma warning restore CS0649
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Culture_TR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ecommerce.Admin.Resources.Culture_TR", typeof(Culture_TR).Assembly);
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtre Grubu Ekle.
        /// </summary>
        public static string AddFilterGroupText {
            get {
                return ResourceManager.GetString("AddFilterGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtre Ekle.
        /// </summary>
        public static string AddFilterText {
            get {
                return ResourceManager.GetString("AddFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamam.
        /// </summary>
        public static string ApplyFilterText {
            get {
                return ResourceManager.GetString("ApplyFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temizle.
        /// </summary>
        public static string ClearFilterText {
            get {
                return ResourceManager.GetString("ClearFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İçeriyorsa.
        /// </summary>
        public static string ContainsText {
            get {
                return ResourceManager.GetString("ContainsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İçermiyorsa.
        /// </summary>
        public static string DoesNotContainText {
            get {
                return ResourceManager.GetString("DoesNotContainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veri bulunamadı..
        /// </summary>
        public static string EmptyText {
            get {
                return ResourceManager.GetString("EmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metinle biten.
        /// </summary>
        public static string EndsWithText {
            get {
                return ResourceManager.GetString("EndsWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eşittir.
        /// </summary>
        public static string EqualsText {
            get {
                return ResourceManager.GetString("EqualsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Büyüktür veya Eşittir.
        /// </summary>
        public static string GreaterThanOrEqualsText {
            get {
                return ResourceManager.GetString("GreaterThanOrEqualsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Büyüktür.
        /// </summary>
        public static string GreaterThanText {
            get {
                return ResourceManager.GetString("GreaterThanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boş.
        /// </summary>
        public static string IsEmptyText {
            get {
                return ResourceManager.GetString("IsEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dolu.
        /// </summary>
        public static string IsNotEmptyText {
            get {
                return ResourceManager.GetString("IsNotEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boş olmayan.
        /// </summary>
        public static string IsNotNullText {
            get {
                return ResourceManager.GetString("IsNotNullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boş.
        /// </summary>
        public static string IsNullText {
            get {
                return ResourceManager.GetString("IsNullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Küçüktür Veya Eşittir.
        /// </summary>
        public static string LessThanOrEqualsText {
            get {
                return ResourceManager.GetString("LessThanOrEqualsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Küçüktür.
        /// </summary>
        public static string LessThanText {
            get {
                return ResourceManager.GetString("LessThanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eşit değildir.
        /// </summary>
        public static string NotEqualsText {
            get {
                return ResourceManager.GetString("NotEqualsText", resourceCulture);
            }
        }
    }
}
